<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Godox.Desktop</AssemblyName>
    <RootNamespace>Godox.Desktop</RootNamespace>
    <Authors>m9agrest</Authors>
    <Copyright>Copyright (c) 2026 m9agrest</Copyright>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/m9agrest/Godox</RepositoryUrl>
    <Version>0.2.1</Version>
    <ApplicationIcon>../../assets/godox.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup><FrameworkReference Include="Microsoft.AspNetCore.App" /></ItemGroup>
  <ItemGroup><Resource Include="../../assets/godox.ico" Link="Assets/godox.ico" /></ItemGroup>
  <ItemGroup><Using Remove="System.Windows.Forms" /><Using Remove="System.Drawing" /></ItemGroup>
</Project>
